
def error():
    print ("FOOL OF A TOOK!")
    exit()